{
    'name': 'Deferred Expense Schedule',
    'version': '17.0',
    'category': 'Account',
    'summary': 'Deferred Expense Schedule',
    'author': 'Divergent Catalist ERP Solutions',
    'company': 'Divergent Catalist ERP Solutions',
    'maintainer': 'Divergent Catalist ERP Solutions',
    'depends': ['base', 'account','mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'security/record_rule.xml',
        'data/data.xml',
        'data/monthly_data.xml',
        'views/expense.xml',
        'views/monthly_expense.xml',
        'views/account_journal.xml',
        'views/account_move.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
